spring:
  application:
    name: ops-app-2

server:
  port: 8081

app:
  profile: ${PROFILE:default}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      probes:
        enabled: true
      # livenessState:
      #   enabled: true
      # readinessState:
      #   enabled: true
    prometheus:
      access: read only
  metrics:
    tags:
      application: ${spring.application.name}
      profile: ${app.profile:default}
